## The 'makeCacheMatrix' holds the value of inverse of a matrix.
## When the second function has to calculate the inverse of a matrix
## It is retrieved from the list generated by the 'makeCacheMatrix' func
## if earlier an inverse was calculated. If not calculated earlier,
## The 'cacheSolve' calculates the inverse and returns it.

## The 'makeCacheMatrix' function takes in a matrix
## and it generates a list which has an inverse value
## of the input matrix along with other elements like
## the matrix itself. This function utilizes the lexical
## scoping in R to cache the value of inverse of the
## input matrix using the operator '<<-'

makeCacheMatrix <- function(x) {
  i <- NULL
  set <- function(y) {
    x <<- y
    i <<- NULL
  }
  get <- function()
    x
  setinv <- function(inv)
    i <<- inv
  getinv <- function(inv)
    i
  list(
    set = set,
    get = get,
    setinv = setinv,
    getinv = getinv
  )
}


## The function 'cacheSolve' calculates the inverse
## of the input matrix, if it is not already calculated.
## If it is calculated already, the inverse of that matrix
## retrieved from the list which is generated by the
## 'makeCacheMatrix' function

cacheSolve <- function(x, ...) {
  i <- x$getinv()
  if (!is.null(i)) {
    message("getting cached data")
    return(i)
  }
  data <- x$get()
  i <- solve(data, ...)
  x$setinv(i)
  i
}
